cache:
  paths:
    - /home/gradle/.gradle
    - ./build


stages:
  - build
  - deploy maven

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


before_script:
  - java -version
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - echo $CI_COMMIT_BRANCH


buildjdk8:
  image: gradle:7.0.0-jdk8
  stage: build
  retry: 2
  script: gradle build
  tags:
    - jdk8


buildjdk11:
  image: gradle:7.0.0-jdk11
  stage: build
  retry: 2
  script: gradle build
  tags:
    - jdk11


.buildjdk16:
  image: gradle:7.0.0-jdk16
  stage: build
  retry: 2
  script: gradle build


deployjdk8:
  image: gradle:7.0.0-jdk8
  stage: deploy maven
  script:
    - TAG=$CI_COMMIT_TAG
    - VERSION=${TAG:1}
    - echo kotlin.code.style=official > ./gradle.properties
    - echo user=$USERNAME >> ./gradle.properties
    - echo passwd=$PASSWORD >> ./gradle.properties
    - echo projectVersion=$VERSION >> ./gradle.properties
    - echo mavenUrl=$URL >> ./gradle.properties
    - cat ./gradle.properties
    - gradle publish
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]?.+/
  retry: 2
  tags:
    - jdk8


.deployjdk11:
  image: gradle:7.0.0-jdk11
  stage: deploy maven
  script:
    - TAG=$CI_COMMIT_TAG
    - VERSION=${TAG:1}
    - echo kotlin.code.style=official > ./gradle.properties
    - echo user=$USERNAME >> ./gradle.properties
    - echo passwd=$PASSWORD >> ./gradle.properties
    - echo projectVersion=$VERSION-jdk11 >> ./gradle.properties
    - echo mavenUrl=$URL >> ./gradle.properties
    - cat ./gradle.properties
    - gradle publish
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]?.+/
  retry: 2
  tags:
    - jdk11


.deployjdk16:
  image: gradle:7.0.0-jdk16
  stage: deploy maven
  script:
    - TAG=$CI_COMMIT_TAG
    - VERSION=${TAG:1}
    - echo kotlin.code.style=official > ./gradle.properties
    - echo user=$USERNAME >> ./gradle.properties
    - echo passwd=$PASSWORD >> ./gradle.properties
    - echo projectVersion=$VERSION-jdk16 >> ./gradle.properties
    - echo mavenUrl=$URL >> ./gradle.properties
    - cat ./gradle.properties
    - gradle publish
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]?.+/
  retry: 2


#deployjdk8snapshots:
#  image: gradle:7.0.0-jdk8
#  stage: deploy maven
#  script:
#    - STR=$CI_COMMIT_TAG
#    - TAG=${STR:1}
#    - VERSION=${TAG%%-*}
#    - echo kotlin.code.style=official > ./gradle.properties
#    - echo user=$USERNAME >> ./gradle.properties
#    - echo passwd=$PASSWORD >> ./gradle.properties
#    - echo projectVersion=$VERSION-jdk8-SNAPSHOT >> ./gradle.properties
#    - echo mavenUrl=$SNAPSHOTSURLURL >> ./gradle.properties
#    - cat ./gradle.properties
#    - gradle publish
#  except:
#    - product
#    - dev
#    - master
#  only:
#    variables:
#      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]-SNAPSHOT/
#  retry: 2
#  tags:
#    - jdk8
#
#
#deployjdk11snapshots:
#  image: gradle:7.0.0-jdk11
#  stage: deploy maven
#  script:
#    - STR=$CI_COMMIT_TAG
#    - TAG=${STR:1}
#    - VERSION=${TAG%%-*}
#    - echo kotlin.code.style=official > ./gradle.properties
#    - echo user=$USERNAME >> ./gradle.properties
#    - echo passwd=$PASSWORD >> ./gradle.properties
#    - echo projectVersion=$VERSION-jdk11-SNAPSHOT >> ./gradle.properties
#    - echo mavenUrl=$SNAPSHOTSURLURL >> ./gradle.properties
#    - cat ./gradle.properties
#    - gradle publish
#  except:
#    - product
#    - dev
#    - master
#  only:
#    variables:
#      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]-SNAPSHOT/
#  retry: 2
#  tags:
#    - jdk11
#
#
#.deployjdk16snapshots:
#  image: gradle:7.0.0-jdk16
#  stage: deploy maven
#  script:
#    - STR=$CI_COMMIT_TAG
#    - TAG=${STR:1}
#    - VERSION=${TAG%%-*}
#    - echo kotlin.code.style=official > ./gradle.properties
#    - echo user=$USERNAME >> ./gradle.properties
#    - echo passwd=$PASSWORD >> ./gradle.properties
#    - echo projectVersion=$VERSION-jdk16-SNAPSHOT >> ./gradle.properties
#    - echo mavenUrl=$SNAPSHOTSURLURL >> ./gradle.properties
#    - cat ./gradle.properties
#    - gradle publish
#  except:
#    - product
#    - dev
#    - master
#  only:
#    variables:
#      - $CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9].[0-9]+/
#  retry: 2
#
