image: gradle:7.0.0-jdk16
cache:
  paths:
    - /home/gradle/.gradle
stages:
  - build jar
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
build:
  stage: build jar
  retry: 2
  script: gradle build