image: gradle:7.0.0-jdk16
cache:
  paths:
    - /home/gradle/.gradle
stages:
  - build jar
  - deploy maven

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
build:
  stage: build jar
  retry: 2
  script: gradle build

deploy:
  stage: deploy maven
  script:
    - TAG=$CI_COMMIT_TAG
    - VERSION=${TAG:1}
    - echo kotlin.code.style=official > ./gradle.properties
    - echo CI_JOB_TOKEN=$CI_JOB_TOKEN >> ./gradle.properties
    - echo projectVersion=$VERSION >> ./gradle.properties
    - cat ./gradle.properties
    - gradle publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[v][0-9][0-9]?.[0-9]+.[0-9]+/'
